/* ============================================================
   bide guest TV — paste the built map into the pages

       node tools/map/build.mjs && node tools/map/inject.mjs

   The map lives inline in two places: the full-screen map page, and the
   poster that links to it from the NC500 guide. Keeping them in step by
   hand is exactly the sort of thing that goes wrong quietly, so the
   generated fragment is written into both between marker comments.

   The two differ in two respects. The page fits the whole map into the
   frame; the poster is a 16:9 card, so it crops instead — otherwise the
   map would sit in the middle of the card in a letterbox.

   And the pins are only links on the page. In the card the whole thing
   is one link to the map, so the pins are drawn but not focusable:
   otherwise pressing down off the row above lands on a pin the size of
   a pea, half of it cropped outside the card, and the guest is left
   looking at a focus ring on nothing.
   ============================================================ */

import fs from 'node:fs/promises';
import path from 'node:path';

const HERE = import.meta.dirname;
const ROOT = path.resolve(HERE, '../..');

const which = process.argv[2] || 'coast';
const SOURCES = {
  coast: {
    file: 'coast.svg',
    className: 'map map--coast',
    targets: [
      { file: 'public/nc500/map/index.html', fit: 'xMidYMid meet', indent: '    ', pins: true },
      /* The poster is wider than the map, so it crops. Anchored to the
         bottom edge: the coast and the pins are down there, and Orkney is
         the part that can afford to go. */
      { file: 'public/nc500/index.html', fit: 'xMidYMax slice', indent: '        ', pins: false }
    ]
  },
  town: {
    file: 'town.svg',
    className: 'map map--town',
    targets: [
      { file: 'public/eat/map/index.html', fit: 'xMidYMid meet', indent: '    ', pins: true },
      { file: 'public/eat/index.html', fit: 'xMidYMid slice', indent: '        ', pins: false }
    ]
  }
};
const SRC = SOURCES[which];
if (!SRC) throw new Error(`no such map: ${which} (have ${Object.keys(SOURCES).join(', ')})`);

const fragment = await fs.readFile(path.join(HERE, SRC.file), 'utf8');

const vb = /viewBox 0 0 (\d+) (\d+)/.exec(fragment);
if (!vb) throw new Error('coast.svg does not say what its viewBox is');
const [, W, H] = vb;

/* The generator's own comments are for whoever opens coast.svg, not for
   the television. */
const shapes = fragment
  .split('\n')
  .filter(line => !line.startsWith('<!--') && !line.startsWith('     ') && line.trim())
  .join('\n  ');

/* The land is built on a rectangle larger than the picture, so that it
   can be closed off out of sight. Without a clip it spills into the
   letterboxing either side of the map and the frame stops looking like
   a frame. */
/* Each pin is one line: <a href=… class="pin-hit" tabindex="0">…</a>.
   Turning it into a <g class="pin"> keeps every circle and label
   exactly where it was, and drops the class bide.js hunts for, so the
   pin leaves the focus order rather than becoming a <g> the navigation
   still tries to focus. */
const inert = markup => markup
  .replace(/<a href="[^"]*" class="pin-hit" tabindex="0">/g, '<g class="pin">')
  .replace(/<\/a>/g, '</g>');

const svg = (fit, pins) => [
  `<svg class="${SRC.className}" viewBox="0 0 ${W} ${H}" preserveAspectRatio="${fit}" aria-hidden="false">`,
  `  <defs><clipPath id="mapclip"><rect x="0" y="0" width="${W}" height="${H}" rx="3"/></clipPath></defs>`,
  `  <g clip-path="url(#mapclip)">`,
  `    <rect class="sea" x="0" y="0" width="${W}" height="${H}"/>`,
  `    ${(pins ? shapes : inert(shapes)).split('\n').join('\n  ')}`,
  `  </g>`,
  `</svg>`
].join('\n');

const TARGETS = SRC.targets;

const BEGIN = '<!-- MAP:BEGIN — generated by tools/map/build.mjs, injected by tools/map/inject.mjs -->';
const END = '<!-- MAP:END -->';

for (const t of TARGETS) {
  const file = path.join(ROOT, t.file);
  let html = await fs.readFile(file, 'utf8');

  const block = [BEGIN, svg(t.fit, t.pins !== false), END]
    .join('\n')
    .split('\n')
    .join('\n' + t.indent);

  const from = html.indexOf(BEGIN);
  if (from === -1) throw new Error(`${t.file}: no MAP:BEGIN marker — add one where the map goes`);
  const to = html.indexOf(END, from);
  if (to === -1) throw new Error(`${t.file}: MAP:BEGIN with no MAP:END`);

  html = html.slice(0, from) + block + html.slice(to + END.length);
  await fs.writeFile(file, html);
  console.log(`  ${t.file}  (${t.fit}${t.pins === false ? ', pins not focusable' : ''})`);
}

console.log(`${which} map is ${W}x${H}, ${(shapes.length / 1024).toFixed(1)} kB of paths, in ${TARGETS.length} page(s)`);
